export const CATEGORIES = [
  { slug: "fotografi", nameBg: "Фотографи", nameEn: "Photographers" },
  { slug: "videografi", nameBg: "Видеографи", nameEn: "Videographers" },
  { slug: "dj", nameBg: "DJ", nameEn: "DJs" },
  { slug: "vodeshti", nameBg: "Водещи", nameEn: "Hosts & MCs" },
  { slug: "restoranti", nameBg: "Ресторанти", nameEn: "Restaurants" },
  { slug: "hoteli", nameBg: "Хотели", nameEn: "Hotels" },
  { slug: "svatbeni-zali", nameBg: "Сватбени зали", nameEn: "Wedding venues" },
  { slug: "dekoratori", nameBg: "Декоратори", nameEn: "Decorators" },
  { slug: "floristi", nameBg: "Флористи", nameEn: "Florists" },
  { slug: "sladkarnitsi", nameBg: "Сладкарници", nameEn: "Cake shops" },
  { slug: "grimyori", nameBg: "Гримьори", nameEn: "Makeup artists" },
  { slug: "frizyori", nameBg: "Фризьори", nameEn: "Hair stylists" },
  { slug: "roklia-dizayneri", nameBg: "Дизайнери на рокли", nameEn: "Dress designers" },
  { slug: "kostyumi", nameBg: "Костюми", nameEn: "Suits" },
  { slug: "transport", nameBg: "Транспорт", nameEn: "Transport" },
  { slug: "svatbeni-agentsii", nameBg: "Сватбени агенции", nameEn: "Wedding planners" },
  { slug: "drugi", nameBg: "Други сватбени услуги", nameEn: "Other wedding services" },
] as const;

export const REGIONS = [
  { slug: "blagoevgrad", name: "Благоевград", city: { slug: "blagoevgrad", name: "Благоевград" } },
  { slug: "burgas", name: "Бургас", city: { slug: "burgas", name: "Бургас" } },
  { slug: "varna", name: "Варна", city: { slug: "varna", name: "Варна" } },
  { slug: "veliko-tarnovo", name: "Велико Търново", city: { slug: "veliko-tarnovo", name: "Велико Търново" } },
  { slug: "vidin", name: "Видин", city: { slug: "vidin", name: "Видин" } },
  { slug: "vratsa", name: "Враца", city: { slug: "vratsa", name: "Враца" } },
  { slug: "gabrovo", name: "Габрово", city: { slug: "gabrovo", name: "Габрово" } },
  { slug: "dobrich", name: "Добрич", city: { slug: "dobrich", name: "Добрич" } },
  { slug: "kardzhali", name: "Кърджали", city: { slug: "kardzhali", name: "Кърджали" } },
  { slug: "kyustendil", name: "Кюстендил", city: { slug: "kyustendil", name: "Кюстендил" } },
  { slug: "lovech", name: "Ловеч", city: { slug: "lovech", name: "Ловеч" } },
  { slug: "montana", name: "Монтана", city: { slug: "montana", name: "Монтана" } },
  { slug: "pazardzhik", name: "Пазарджик", city: { slug: "pazardzhik", name: "Пазарджик" } },
  { slug: "pernik", name: "Перник", city: { slug: "pernik", name: "Перник" } },
  { slug: "pleven", name: "Плевен", city: { slug: "pleven", name: "Плевен" } },
  { slug: "plovdiv", name: "Пловдив", city: { slug: "plovdiv", name: "Пловдив" } },
  { slug: "razgrad", name: "Разград", city: { slug: "razgrad", name: "Разград" } },
  { slug: "ruse", name: "Русе", city: { slug: "ruse", name: "Русе" } },
  { slug: "silistra", name: "Силистра", city: { slug: "silistra", name: "Силистра" } },
  { slug: "sliven", name: "Сливен", city: { slug: "sliven", name: "Сливен" } },
  { slug: "smolyan", name: "Смолян", city: { slug: "smolyan", name: "Смолян" } },
  { slug: "sofia-grad", name: "София-град", city: { slug: "sofia", name: "София" } },
  { slug: "sofia-oblast", name: "София-област", city: { slug: "samokov", name: "Самоков" } },
  { slug: "stara-zagora", name: "Стара Загора", city: { slug: "stara-zagora", name: "Стара Загора" } },
  { slug: "targovishte", name: "Търговище", city: { slug: "targovishte", name: "Търговище" } },
  { slug: "haskovo", name: "Хасково", city: { slug: "haskovo", name: "Хасково" } },
  { slug: "shumen", name: "Шумен", city: { slug: "shumen", name: "Шумен" } },
  { slug: "yambol", name: "Ямбол", city: { slug: "yambol", name: "Ямбол" } },
] as const;
